### ISSUE TITLE
Add Autosuggest for helm charts 

### ISSUE THREAD

**Issue by ruf-io** [do-community/kubernetes-tool#16]
### Feature description
Autosuggest dropdown in the input field of the helm chart
![image](https://user-images.githubusercontent.com/11527560/68234517-5f147480-ffcf-11e9-8d75-18fdc057cf31.png)

### How the feature is useful
This would help clarify the formatting that needs to be used to specify a particular helm chart.

**Comment by darrenjennings** [comment]
hello! vue-autosuggest author here. Just curious is this tool being used on the community website somewhere?

**Comment by MattIPv4** [comment]
Hey @darrenjennings,

Awesome, thanks for such a great package!

This tool hasn't yet been deployed on the Community site, we're still working on this in the background.

**Comment by darrenjennings** [comment]
@MattIPv4 you're welcome! this kubenetes tool is nice. Let me know if I can be of any help. Happy to review or help with development on the autosuggest code portions.
